[CI][Bench] Fix for pip packages and fix md file path
Plus minor cleanups and extra comments

diff --git a/.github/workflows/benchmarks-reusable.yml b/.github/workflows/benchmarks-reusable.yml
--- a/.github/workflows/benchmarks-reusable.yml
+++ b/.github/workflows/benchmarks-reusable.yml
@@ -37,14 +37,13 @@ on:
       runner:
         required: true
         type: string
-        default: 'level_zero_PERF'
 
 permissions:
   contents: write
   pull-requests: write
 
 jobs:
-  e2e-build-hw:
+  benchmarks:
     name: Build SYCL, UR, run Compute Benchmarks
     strategy:
       matrix:
@@ -54,7 +53,6 @@ jobs:
           }
         ]
         build_type: [Release]
-        compiler: [{c: clang, cxx: clang++}]
 
     runs-on: "${{ inputs.runner }}"
 
@@ -92,12 +90,11 @@ jobs:
         ref: benchmark-results
         path: results-repo
 
-    - name: Create virtual environment
-      run: python -m venv .venv
-
-    - name: Activate virtual environment and install pip packages
+    - name: Install Python requirements in venv
       run: |
+        python -m venv .venv
         source .venv/bin/activate
+        echo "$PATH" >> $GITHUB_PATH
         pip install -r sc/devops/scripts/benchmarks/requirements.txt
 
     - name: Checkout SYCL
@@ -175,7 +172,6 @@ jobs:
     - name: Run benchmarks
       id: benchmarks
       run: >
-        source .venv/bin/activate &&
         taskset -c ${{ env.CORES }} ./sc/devops/scripts/benchmarks/main.py
         ~/ur_bench_workdir
         --sycl ${{ github.workspace }}/sycl_build
@@ -189,9 +185,10 @@ jobs:
         --preset ${{ inputs.preset }}
         ${{ inputs.bench_script_params }}
 
+    # In case it failed to add a comment, we can still print the results.
     - name: Print benchmark results
-      run: |
-        cat ${{ github.workspace }}/sc/devops/scripts/benchmarks/benchmark_results.md || true
+      if: ${{ always() }}
+      run: cat ${{ github.workspace }}/benchmark_results.md || true
 
     - name: Add comment to PR
       uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
@@ -201,7 +198,7 @@ jobs:
           let markdown = ""
           try {
             const fs = require('fs');
-            markdown = fs.readFileSync('sc/devops/scripts/benchmarks/benchmark_results.md', 'utf8');
+            markdown = fs.readFileSync('${{ github.workspace }}/benchmark_results.md', 'utf8');
           } catch(err) {
           }
 
@@ -227,7 +224,7 @@ jobs:
         git config --global user.email "actions@github.com"
 
         for attempt in {1..5}; do
-          echo "Attempt $attempt to push changes"
+          echo "Attempt #$attempt to push changes"
 
           rm -f data.json
           cp ${{ github.workspace }}/sc/devops/scripts/benchmarks/html/data.json .
